/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab11;

import java.util.Random;
import java.util.Scanner;

/*
 course: CSC190
 project: lab11
 date:4-6
 author: Phillip Ables
 purpose: 
The computer randomly generates a secret integer number in range [0, 999]. 
Then the user keeps guessing the secret number until the correct one is entered, or the user has tried 10 times. 
If the user guesses the correct number within 10 times, the program displays “Congratulations, you won the game! You got it in ??? tries”, and then exits. Otherwise, the program displays “Sorry, you lost the game! The answer should be ???”. 
Every time when the user enters a wrong number, the program should give the user a clue whether the entered number is too small or too large.
*/
class NumberGuessingGame {
    int secret; // secret number generated by the computer
    //constructor to initailize secret by generating a random integer

    //in range 0~n
    NumberGuessingGame(int n){
        
    }
    
    void playGame(){
        
    }
}

public class Lab11 {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        Random rnd = new Random();
        String res;
        
        do {
            int n = rnd.nextInt(1000);
            NumberGuessingGame myGame = new NumberGuessingGame(n);
            myGame.playGame();
            
            System.out.print("play again?");
            res = in.next();
        }while (res.charAt(0) == 'y' || res.charAt(0) == 'Y');
        
        System.out.println("Thanks for playing my game!");
    }
    
}
